### ISSUE TITLE
toks for linux-64bit installed as non-executable

### ISSUE THREAD

**Issue by ZenithDK** [thomasthorsen/SublimeToks#4]
I had problems with toks not being able to run as the check initially failed. I managed to print the path it is looking for (maybe that should be part of the output if it fails) and the file was located in the correct location. A little bit of digging revealed it was due to it not being executable, and changing the permissions fixed this problem.
I would suggest changing the error printed if the file is located, but not executable, and see if the binary can be installed as executable also.

**Comment by thomasthorsen** [comment]
Looks like everything is in order:

──[tthorsen@ttbuntu:~/git]──
> git clone git@github.com:thomasthorsen/SublimeToks.git
Cloning into 'SublimeToks'...
remote: Counting objects: 61, done.
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 61
Receiving objects: 100% (61/61), 943.82 KiB | 824.00 KiB/s, done.
Resolving deltas: 100% (33/33), done.
Checking connectivity... done.
──[tthorsen@ttbuntu:~/git]──
> cd SublimeToks/
──[tthorsen@ttbuntu:~/git/SublimeToks]──
> git ls-files -s toks/linux-64bit
100755 ab143969983100b314112ddf79d4a6476d04842a 0	toks/linux-64bit/toks
──[tthorsen@ttbuntu:~/git/SublimeToks]──
> ls -l toks/linux-64bit/toks 
-rwxrwxr-x 1 tthorsen tthorsen 951160 Apr  6 23:26 toks/linux-64bit/toks

There doesn't appear to be any one else having this issue (including myself when installing via Package Control), so I am thinking you must be doing something odd?

**Comment by ZenithDK** [comment]
Fair enough as for it being an error on my side, but could you add more debugging to that part of the code path?

**Comment by thomasthorsen** [comment]
I've seen this on at least one occasion. I have no explanation for why that is (it is beyond my control what happens in package control), but I have some code to work around it by setting the execute bit explicitly on init of the plugin.
