### ISSUE TITLE
Install SublimeToks as zip

### ISSUE THREAD

**Issue by ZenithDK** [thomasthorsen/SublimeToks#5]
It seems like the new way of distributing packages in Package Control is via zipped packages named "<package>.sublime-package" and put them in ".config/sublime-tex-3/Installed Packages"
That is at least how all my other packages (except Anaconda) have installed themselves.
I think the ".config/sublime-tex-3/Packages" directory is for ST packages that it needs internally.

**Comment by thomasthorsen** [comment]
This is working as intended. The package contains binaries for toks and therefore needs to be extracted to be able to execute these binaries.
